config/routes.rb
Rails.application.routes.draw do

  resources :categories do
  	resources :comments
  end
  resources :category_posts do
    resources :comments
  end

  root "categories#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :category_posts
	has_many :comments, as: :commentable, :dependent => :destroy
  validates :name, presence: true, format: { with: /\A((\b[A-Z][A-Za-z]{2,}\b)\s*)((\b[A-Za-z]{2,}\b)\s*)[\.]{1,}\Z/, message: "Your name must be at least 2 words and minimum is 2 characters with point and first letter id capitale" }
	
end

app/models/category_post.rb
class CategoryPost < ApplicationRecord
	has_and_belongs_to_many :categories
	has_many :comments, as: :commentable, :dependent => :destroy
	validates :name, presence: true, format: { with: /\A((\b[A-Z][A-Za-z]{2,}\b)\s*)((\b[A-Za-z]{2,}\b)\s*)[\.]{1,}\Z/, message: "Your name must be at least 2 words and minimum is 2 characters with point and first letter id capitale" }
	mount_uploader :file, FileUploader
	accepts_nested_attributes_for :categories, reject_if: :all_blank, allow_destroy: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :commentable, polymorphic: true

	validates :author, presence: true, format: { with: /\A((\b[A-Z][A-Za-z]{2,}\b)\s*)((\b[A-Z][A-Za-z]{2,}\b)\s*)[\.]{1,}\Z/, message: "Your author must be at least 2 words and minimum is 2 characters with point and first letter id capitale" }
	validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :name, presence: true, format: { with: /\A((\b[A-Z][A-Za-z]{2,}\b)\s*)((\b[A-Za-z]{2,}\b)\s*)[\.]{1,}\Z/, message: "Your name must be at least 2 words and minimum is 2 characters with point and first letter id capitale" }
	mount_uploader :file, FileUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, :only => [:show, :edit, :update, :destroy]

  def index
  	@categories = Category.all
  end

  def show
    @category_posts = @category.category_posts
  end

  def new
  	@category = Category.new
  end

  def create
  	@category = Category.new(category_params)

  	respond_to do |format|
  		if @category.save
  			format.html { redirect_to @category }
  			flash[:success] = "Successfully created..."
  		else
  			format.html { render :new }
  			flash[:danger] = "Error..."
  			format.json { render json: @category.errors, status: :unprocessable_entity }
  		end
  	end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category }
        flash[:success] = "Successfully updated..."
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        flash[:danger] = "Error..."
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
      respond_to do |format|
      format.html { redirect_to categories_url }
      flash[:success] = "Successfully destroyed..."
      format.json { head :no_content }
    end
  end

  private

  def category_params
  	params.require(:category).permit(:name, :description)
  end

  def set_category
  	@category = Category.find(params[:id])
  end
end

app/controllers/category_posts_controller.rb
class CategoryPostsController < ApplicationController
	before_action :set_category_post, :only => [:show, :edit, :update, :destroy]

  def index
  	@category_posts = CategoryPost.all
  end

  def show
    @categories = @category_post.categories
  end

  def edit
  end

  def new
  	@category_post = CategoryPost.new
  end

  def create
  	@category_post = CategoryPost.new(category_post_params)

  	respond_to do |format|
  		if @category_post.save
  			format.html { redirect_to @category_post }
  			flash[:success] = "Successfully created..."
  		else
  			format.html { render :new }
  			flash[:danger] = "Error..."
  			format.json { render json: @category_post.errors, status: :unprocessable_entity }
  		end
  	end
  end

  def update
    respond_to do |format|
      if @category_post.update(category_post_params)
        format.html { redirect_to @category_post }
        flash[:success] = "Successfully updated..."
        format.json { render :show, status: :ok, location: @category_post }
      else
        format.html { render :edit }
        flash[:danger] = "Error..."
        format.json { render json: @category_post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category_post.destroy
      respond_to do |format|
      format.html { redirect_to category_posts_url }
      flash[:success] = "Successfully destroyed..."
      format.json { head :no_content }
    end
  end

  private

  def category_post_params
  	params.require(:category_post).permit(:name, :description, :file, :category_ids =>[])
  end

  def set_category_post
  	@category_post = CategoryPost.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable, only: :create

  def create
    @comment = @commentable.comments.new comment_params
    @comment.save
    respond_to do |format|
      format.js { render :nothing => true, :head => :ok } 
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :content)
  end

  def find_commentable
	  if params[:category_id]
	    @commentable = Category.find_by_id(params[:category_id]) 
	  elsif params[:category_post_id]
	    @commentable = CategoryPost.find_by_id(params[:category_post_id])
	  end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_category.html.haml
= link_to category.name, category_path(category), class: "btn btn-outline-primary"

app/views/categories/_form.html.haml
= simple_form_for @category do |f|
  = f.input :name, input_html: { placeholder: "Название", class: "form-control"}, label: false
  = f.input :description, input_html: { placeholder: "Описание", class: "form-control", rows: "3"}, label: false
  = f.button :button, "Сохранить", class: "btn btn-success", id: "submitCategory", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Сохранение..."}

app/views/categories/edit.html.haml
%section.section-new-category
  .container
    .row
      .col-12
        %h1 Редактирование Категории
      .col-12
        .form-category
          = render "form"

app/views/categories/index.html.haml
%section.category-section.my-4
  .container
    .row
      .col-12
        %h1 Categories
      .col-12.mb-4
        = render partial: "categories/category", collection: @categories, as: :category
      .col-12
        = link_to "Создать Категорию", new_category_path, class: "btn btn-primary", id: "newCategory"

app/views/categories/new.html.haml
%section.section-new-category
  .container
    .row
      .col-12
        %h1 Создание Категории
      .col-12
        .form-category
          = render "form"
        

app/views/categories/show.html.haml
%section.category-section.my-4
  .container
    .row
      .col-12
        %h1
          = @category.name
        %p
          = simple_format(@category.description)
      .col-12
        = link_to "Редактировать", edit_category_path(@category), class: "btn btn-warning", id: "editCategory"
        = link_to "Удалить", category_path(@category), method: :delete, class: "btn btn-danger", id: "deleteCategory", data: { confirm: 'Are you certain you want to delete this?' }
    .row
      .col-12
        %h1 Posts
      = render partial: "category_posts/category_post", collection: @category_posts, as: :category_post

%section.comments-section
  .container
    .row
      .col-12
        #comments.mb-4
          = render partial: "comments/comments", locals: {commentable: @category}
        = render partial: "comments/form", locals: {commentable: @category}

app/views/category_posts/_category_post.html.haml
= link_to category_post_path(category_post) do
  .col-12.col-md-6.col-lg-4
    .card
      = image_tag category_post.file, class: "img-fluid"
      .card-body
        %h5.card-title
          = category_post.name
        %p
          = category_post.description.truncate(50) if category_post.description.present?

app/views/category_posts/_form.html.haml
= simple_form_for @category_post do |f|
  = f.input :name, input_html: { placeholder: "Заголовок", class: "form-control"}, label: false
  = f.input :description, input_html: { placeholder: "Описание", class: "form-control", rows: "3"}, label: false
  = f.input :file, label: false
  = f.input :category_ids, as: :check_boxes, collection: Category.all.map { |m| [m.name, m.id] }, label: "Categories"
  = f.button :button, "Сохранить", class: "btn btn-success", id: "submitCategoryPost", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Сохранение..."}

app/views/category_posts/edit.html.haml
%section.section-new-category
  .container
    .row
      .col-12
        %h1 Редактирование Поста
      .col-12
        .form-category
          = render "form"

app/views/category_posts/index.html.haml
%section.category_post_posts-section
  .container
    .row
      .col-12
        %h1 Posts
      = render partial: "category_posts/category_post", collection: @category_posts, as: :category_post
      .col-12
        = link_to "Создать Пост", new_category_post_path, class: "btn btn-primary", id: "newCategoryPost"

app/views/category_posts/new.html.haml
%section.section-new-category
  .container
    .row
      .col-12
        %h1 Создание Поста
      .col-12
        .form-category
          = render "form"

app/views/category_posts/show.html.haml
%section.category_post-post-section.my-4
  .container
    .row
      .col-12.col-md-8.col-lg-6
        %h1
          = @category_post.name
        .image-post
          = image_tag @category_post.file, class: "img-fluid"
        .categories
          - @categories.each do |category|
            = link_to category_path(category) do
              %span.badge.badge-primary
                = category.name
        %p
          = simple_format(@category_post.description)
      .col-12
        = link_to "Редактировать", edit_category_post_path(@category_post), class: "btn btn-warning", id: "editCategoryPost"
        = link_to "Удалить", category_post_path(@category_post), method: :delete, class: "btn btn-danger", id: "deleteCategoryPost", data: { confirm: 'Are you certain you want to delete this?' }

%section.comments-section
  .container
    .row
      .col-12
        #comments.mb-4
          = render partial: "comments/comments", locals: {commentable: @category_post}
        = render partial: "comments/form", locals: {commentable: @category_post}

app/views/comments/_comments.html.haml
%h3.mb-4 Комментарии
- commentable.comments.each do |comment|
  .media.mb-4
    %span.mr-3
      = comment.author
    .media-body
      = comment.content

app/views/comments/_form.html.haml
= simple_form_for [commentable, Comment.new], remote: true do |f|
  = f.input :author, input_html: { placeholder: "Имя", class: "form-control"}, label: false
  = f.input :content, input_html: { placeholder: "Комментарий", class: "form-control"}, label: false
  = f.button :button, "Сохранить", class: "btn btn-success", id: "submitCommit", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Сохранение..."}

app/views/comments/create.js.erb
$('#comments').html("<%= j (render partial: 'comments/comments', locals: {commentable: @commentable} ) %>");
$('#new_comment')[0].reset();

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{:href => "#"} MassMedia
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        = link_to "Categories", root_path, class: "nav-link"
      %li.nav-item
        = link_to "Posts", category_posts_path, class: "nav-link"

app/views/layouts/_notification.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= value %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MassMediaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/notification" %>
  	<%= render "layouts/header"%>
    <%= yield %>
  </body>
</html>